### PR TITLE
Kr translate

### PR DESCRIPTION
**Pull request by nark31**
* All Translate

There is no item string 'Steel ingot', 'lapis nugget', 'steel nugget', right?

### CODE REVIEW

**Comment by Shad0wB1ade** [comment]
Hello @nark31, thank you very much for the contribution. I am very sorry that I haven't been able to update the english localizations on github, been really busy IRL. I am working on something and I can not really install github app to update stuff.

There are the things that are missing from here:

items.solarexpansion:steelIngot.name=Steel Ingot
items.solarexpansion:steelNugget.name=Steel Nugget
items.solarexpansion:lapisShard.name=Lapis Shard

Also there is a thing for achievements:

achievement.pageName=Solar Expansion
achievement.solarPanelLeadstoneAch=Basic Power.
achievement.solarPanelLeadstoneAch.desc=Place down a Leadstone Solar Panel.
achievement.solarPanelHardenedAch=Powering Up.
achievement.solarPanelHardenedAch.desc=Place down a Hardened Solar Panel.
achievement.solarPanelRedstoneAch=MORE POWER.
achievement.solarPanelRedstoneAch.desc=Place down a Redstone Solar Panel.
achievement.solarPanelResonantAch=Power Overload.
achievement.solarPanelResonantAch.desc=Place down a Resonant Solar Panel.
achievement.solarPanelAdvancedAch=Power Levels Critical.
achievement.solarPanelAdvancedAch.desc=Place down a Advanced Solar Panel.
achievement.solarPanelUltimateAch=IT'S OVER 9000!
achievement.solarPanelUltimateAch.desc=Place down a Ultimate Solar Panel.

I am very sorry again for not updating github...

**Comment by nark31** [comment]
Ok, Achievements applies to Editable ver, was there any problem?

**Comment by Shad0wB1ade** [comment]
Editable version is not yet updated but the achievements won't be set by me or you, they will be set by the persion configuring the mod. So you don't have to worry about that :P

Thanks again, the update will come later because I am working on something cool (Solar Helmets).

**Comment by Shad0wB1ade** [comment]
Also I wanted to ask you if you would like to do the Solar Helmet lang stuff now to have it ready by the release and not have to wait for next one or not?

In case you do:
items.solarexpansion:solarHelmetLeadstone.name=Leadstone Solar Helmet
items.solarexpansion:solarHelmetHardened.name=Hardened Solar Helmet
items.solarexpansion:solarHelmetRedstone.name=Redstone Solar Helmet
items.solarexpansion:solarHelmetResonant.name=Resonant Solar Helmet
items.solarexpansion:solarHelmetAdvanced.name=Advanced Solar Helmet
items.solarexpansion:solarHelmetUltimate.name=Ultimate Solar Helmet

**Pull request merged**
